variable "ebs_volume_size" {}
variable "instance_type" {}
variable "iam_role_name" {}
variable "vpc_id" {}
variable "ec2_sg_ingress_from_port" {}
variable "ec2_sg_ingress_protocol" {}
variable "ec2_sg_ingress_to_port" {}
variable "cidr_block" {}
variable "cloud" {}
variable "environment" {}
variable "azure_agent_role" {}
variable "pat" {}
variable "ado_url" {}
variable "pool_name" {}
variable "ssh_key_name" {}
variable "autoscaling_desired_size" {}
variable "autoscaling_max_size" {}
variable "autoscaling_min_size" {}
variable "subnet_ids" {}
variable "aws_region" {}